version: '2'

services:
    application:
        container_name: laravel_test_examples_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: laravel_test_examples_workspace
        restart: always
        image: framgia/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: laravel_test_examples_php-fpm
        build: 
            context: ./
        image: varun/laravel-php-fpm
        restart: always
        # image: framgia/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: laravel_test_examples_nginx
        restart: always
        image: framgia/laravel-nginx
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "8000:80"
        links:
            - php-fpm
    data:
        container_name: laravel_test_examples_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    # data_test:
    #     container_name: laravel_test_examples_data_test
    #     image: debian
    #     volumes:
    #         - .docker/mysql_test:/var/lib/mysql
    #         - .docker/data_test:/data
    logs:
        container_name: laravel_test_examples_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/mongodb:/var/log/mongodb
    mysql:
        container_name: laravel_test_examples_mysql
        restart: always
        image: mysql
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    # mysql_test:
    #     container_name: laravel_test_examples_mysql_test
    #     restart: always
    #     image: mysql
    #     volumes_from:
    #         - data_test
    #     expose:
    #         - "3306"
    #     environment:
    #         MYSQL_DATABASE: homestead_test
    #         MYSQL_USER: homestead_test
    #         MYSQL_PASSWORD: secret
    #         MYSQL_ROOT_PASSWORD: root
    redis:
        container_name: laravel_test_examples_redis
        restart: always
        image: redis
        expose:
            - "6379"
        volumes_from:
            - data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        container_name: elasticsearch
        restart: always
        ports:
        - 9200:9200
        - 9300:9300
        environment:
            discovery.type: single-node

    oap:
        image: apache/skywalking-oap-server
        container_name: oap
        depends_on:
        - elasticsearch
        links:
        - elasticsearch
        restart: always
        ports:
        - 11800:11800
        - 12800:12800
        volumes:
        - ./skywaling-config:/skywalking/config:ro

    ui:
        image: apache/skywalking-ui
        container_name: ui
        depends_on:
        - oap
        links:
        - oap
        restart: always
        ports:
        - 8080:8080
        environment:
            collector.ribbon.listOfServers: oap:12800
